-- MySQL Script generated by MySQL Workbench
-- Fri Jun 16 12:24:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bcoaayn1yza5y2d8potc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bcoaayn1yza5y2d8potc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bcoaayn1yza5y2d8potc` DEFAULT CHARACTER SET utf8 ;
USE `bcoaayn1yza5y2d8potc` ;

-- -----------------------------------------------------
-- Table `bcoaayn1yza5y2d8potc`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bcoaayn1yza5y2d8potc`.`categorias` (
  `id_categoria` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcoaayn1yza5y2d8potc`.`jurisdicciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bcoaayn1yza5y2d8potc`.`jurisdicciones` (
  `id_jurisdiccion` INT NOT NULL,
  `jurisdiccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_jurisdiccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcoaayn1yza5y2d8potc`.`organos_legislativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bcoaayn1yza5y2d8potc`.`organos_legislativos` (
  `id_organo_legislativo` INT NOT NULL,
  `organo_legislativo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_organo_legislativo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcoaayn1yza5y2d8potc`.`tipos_normativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bcoaayn1yza5y2d8potc`.`tipos_normativa` (
  `id_tipo_normativa` INT NOT NULL,
  `tipo_normativa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_normativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bcoaayn1yza5y2d8potc`.`leyes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bcoaayn1yza5y2d8potc`.`leyes` (
  `nro_registro` INT NOT NULL AUTO_INCREMENT,
  `nro_normativa` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `palabras_clave` VARCHAR(500) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `categorias_id_categoria` INT NOT NULL,
  `jurisdicciones_id_jurisdiccion` INT NOT NULL,
  `organos_legislativos_id_organo_legislativo` INT NOT NULL,
  `tipos_normativa_id_tipo_normativa` INT NOT NULL,
  PRIMARY KEY (`nro_registro`, `categorias_id_categoria`, `jurisdicciones_id_jurisdiccion`, `organos_legislativos_id_organo_legislativo`, `tipos_normativa_id_tipo_normativa`),
  INDEX `fk_normativas_categorias1_idx` (`categorias_id_categoria` ASC) VISIBLE,
  INDEX `fk_normativas_jurisdicciones1_idx` (`jurisdicciones_id_jurisdiccion` ASC) VISIBLE,
  INDEX `fk_normativas_organos_legislativos1_idx` (`organos_legislativos_id_organo_legislativo` ASC) VISIBLE,
  INDEX `fk_leyes_tipos_normativa1_idx` (`tipos_normativa_id_tipo_normativa` ASC) VISIBLE,
  CONSTRAINT `fk_normativas_categorias1`
    FOREIGN KEY (`categorias_id_categoria`)
    REFERENCES `bcoaayn1yza5y2d8potc`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_normativas_jurisdicciones1`
    FOREIGN KEY (`jurisdicciones_id_jurisdiccion`)
    REFERENCES `bcoaayn1yza5y2d8potc`.`jurisdicciones` (`id_jurisdiccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_normativas_organos_legislativos1`
    FOREIGN KEY (`organos_legislativos_id_organo_legislativo`)
    REFERENCES `bcoaayn1yza5y2d8potc`.`organos_legislativos` (`id_organo_legislativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leyes_tipos_normativa1`
    FOREIGN KEY (`tipos_normativa_id_tipo_normativa`)
    REFERENCES `bcoaayn1yza5y2d8potc`.`tipos_normativa` (`id_tipo_normativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Tabla "tipos_normativa"
INSERT INTO bcoaayn1yza5y2d8potc.tipos_normativa (id_tipo_normativa, tipo_normativa)
VALUES
(1, 'ley'),
(2, 'decreto'),
(3, 'resolución');

-- Tabla "categorias"
INSERT INTO bcoaayn1yza5y2d8potc.categorias (id_categoria, categoria)
VALUES
(1, 'Laboral'),
(2, 'Penal'),
(3, 'Civil'),
(4, 'Comercial'),
(5, 'Familia y Sucesiones'),
(6, 'Agrario y Ambiental'),
(7, 'Minería'),
(8, 'Derecho informático');

-- Tabla "jurisdicciones"
INSERT INTO bcoaayn1yza5y2d8potc.jurisdicciones (id_jurisdiccion, jurisdiccion)
VALUES
(1, 'Nacional'),
(2, 'Provincial');

-- Tabla "organos_legislativos"
INSERT INTO bcoaayn1yza5y2d8potc.organos_legislativos (id_organo_legislativo, organo_legislativo)
VALUES
(1, 'Congreso de la Nación'),
(2, 'Legislatura de Córdoba');

-- Tabla "leyes"
INSERT INTO bcoaayn1yza5y2d8potc.leyes (nro_normativa, fecha, palabras_clave, descripcion, categorias_id_categoria, jurisdicciones_id_jurisdiccion, organos_legislativos_id_organo_legislativo, tipos_normativa_id_tipo_normativa)
VALUES
(20744, '1974-09-05', 'trabajo, laboral', 'Regimen del Contrato de Trabajo', 1, 1, 1, 1),
(27555, '2020-07-30', 'teletrabajo, laboral', 'Regulación de la Modalidad de Teletrabajo', 1, 1, 1, 1),
(7642, '1987-11-25', 'profesional, trabajo', 'Condiciones para el ejercicio profesional de ciencias informáticas', 1, 2, 2, 1);


